# Generated by Django 4.2.7 on 2023-11-27 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productores',
            new_name='Produtos',
        ),
    ]
